<?php
/**
 * Installation Script
 * SchoolPro V2.0.0 - Automated Installation
 * 
 * This script helps you configure and install the application
 */

// Prevent direct access after installation
$installLockFile = __DIR__ . '/.installed';
$configFile = __DIR__ . '/app/config/config.php';
$envFile = __DIR__ . '/.env';

// Check if already installed
if (file_exists($installLockFile) && !isset($_GET['force'])) {
    die("
    <!DOCTYPE html>
    <html>
    <head>
        <title>Already Installed</title>
        <style>
            body { font-family: Arial, sans-serif; max-width: 600px; margin: 100px auto; padding: 20px; background: #f5f5f5; }
            .box { background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
            .btn { display: inline-block; padding: 10px 20px; background: #2563eb; color: white; text-decoration: none; border-radius: 4px; margin-top: 10px; }
            .btn:hover { background: #1d4ed8; }
            .warning { background: #fef3c7; padding: 15px; border-radius: 4px; margin-top: 20px; border-left: 4px solid #f59e0b; }
        </style>
    </head>
    <body>
        <div class='box'>
            <h2>✓ Application Already Installed</h2>
            <p>The application appears to be already installed.</p>
            <div class='warning'>
                <strong>Security Notice:</strong> For security reasons, delete or rename the <code>install.php</code> file after installation.
            </div>
            <a href='index.php' class='btn'>Go to Application</a>
            <a href='?force=1' style='margin-left: 10px;' class='btn' style='background: #dc2626;'>Re-run Installation</a>
        </div>
    </body>
    </html>
    ");
}

$step = $_GET['step'] ?? '1';
$errors = [];
$success = [];

// Process form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $step = $_POST['step'] ?? '1';
    
    if ($step === '1') {
        // Step 1: Database Configuration
        $dbHost = $_POST['db_host'] ?? 'localhost';
        $dbName = $_POST['db_name'] ?? 'masomo_school_db';
        $dbUser = $_POST['db_user'] ?? 'root';
        $dbPass = $_POST['db_pass'] ?? '';
        
        // Test database connection
        try {
            $testConnection = new PDO("mysql:host=$dbHost;charset=utf8mb4", $dbUser, $dbPass);
            $testConnection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Check if database exists, create if not
            $testConnection->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            $success[] = "Database connection successful!";
            $step = '2';
        } catch (PDOException $e) {
            $errors[] = "Database connection failed: " . $e->getMessage();
        }
    } elseif ($step === '2') {
        // Step 2: Create .env file
        $envContent = "# Environment Configuration\n";
        $envContent .= "# Generated by installer on " . date('Y-m-d H:i:s') . "\n\n";
        $envContent .= "ENVIRONMENT=" . ($_POST['environment'] ?? 'production') . "\n\n";
        $envContent .= "# Database Configuration\n";
        $envContent .= "DB_HOST=" . ($_POST['db_host'] ?? 'localhost') . "\n";
        $envContent .= "DB_NAME=" . ($_POST['db_name'] ?? 'masomo_school_db') . "\n";
        $envContent .= "DB_USER=" . ($_POST['db_user'] ?? 'root') . "\n";
        $envContent .= "DB_PASS=" . ($_POST['db_pass'] ?? '') . "\n";
        $envContent .= "DB_CHARSET=utf8mb4\n\n";
        $envContent .= "# Base URL (Auto-detected, can be overridden)\n";
        $envContent .= "BASE_URL=\n\n";
        $envContent .= "APP_NAME=" . ($_POST['app_name'] ?? 'SchoolPro V2.0.0') . "\n";
        $envContent .= "APP_VERSION=1.0.0\n";
        
        if (file_put_contents($envFile, $envContent)) {
            $success[] = ".env file created successfully!";
            $step = '3';
        } else {
            $errors[] = "Failed to create .env file. Please check file permissions.";
        }
    } elseif ($step === '3') {
        // Step 3: Import database
        $dbHost = $_POST['db_host'] ?? 'localhost';
        $dbName = $_POST['db_name'] ?? 'masomo_school_db';
        $dbUser = $_POST['db_user'] ?? 'root';
        $dbPass = $_POST['db_pass'] ?? '';
        $importSchema = isset($_POST['import_schema']);
        
        if ($importSchema) {
            try {
                $pdo = new PDO("mysql:host=$dbHost;dbname=$dbName;charset=utf8mb4", $dbUser, $dbPass);
                $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
                
                $schemaFile = __DIR__ . '/database/schema.sql';
                if (file_exists($schemaFile)) {
                    $sql = file_get_contents($schemaFile);
                    // Split by semicolon and execute each statement
                    $statements = explode(';', $sql);
                    foreach ($statements as $statement) {
                        $statement = trim($statement);
                        if (!empty($statement)) {
                            $pdo->exec($statement);
                        }
                    }
                    $success[] = "Database schema imported successfully!";
                } else {
                    $errors[] = "Schema file not found: database/schema.sql";
                }
            } catch (PDOException $e) {
                $errors[] = "Database import failed: " . $e->getMessage();
            }
        }
        
        // Create uploads directory
        $uploadsDir = __DIR__ . '/public/uploads';
        if (!is_dir($uploadsDir)) {
            mkdir($uploadsDir, 0755, true);
        }
        
        // Create .installed lock file
        file_put_contents($installLockFile, date('Y-m-d H:i:s'));
        
        $step = '4';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolPro Installation</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        .header h1 { font-size: 28px; margin-bottom: 5px; }
        .header p { opacity: 0.9; }
        .content {
            padding: 40px;
        }
        .step-indicator {
            display: flex;
            justify-content: space-between;
            margin-bottom: 40px;
            position: relative;
        }
        .step-indicator::before {
            content: '';
            position: absolute;
            top: 20px;
            left: 0;
            right: 0;
            height: 2px;
            background: #e5e7eb;
            z-index: 1;
        }
        .step {
            position: relative;
            z-index: 2;
            background: white;
            width: 40px;
            height: 40px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            border: 2px solid #e5e7eb;
            color: #9ca3af;
            font-weight: bold;
        }
        .step.active {
            border-color: #667eea;
            color: #667eea;
            background: #eef2ff;
        }
        .step.completed {
            border-color: #10b981;
            background: #10b981;
            color: white;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 8px;
            font-weight: 500;
            color: #374151;
        }
        input[type="text"],
        input[type="password"],
        select {
            width: 100%;
            padding: 12px;
            border: 1px solid #d1d5db;
            border-radius: 6px;
            font-size: 14px;
            transition: border-color 0.3s;
        }
        input:focus, select:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
        }
        .btn {
            background: #667eea;
            color: white;
            padding: 12px 24px;
            border: none;
            border-radius: 6px;
            font-size: 16px;
            font-weight: 500;
            cursor: pointer;
            transition: background 0.3s;
        }
        .btn:hover {
            background: #5568d3;
        }
        .btn-secondary {
            background: #6b7280;
        }
        .btn-secondary:hover {
            background: #4b5563;
        }
        .alert {
            padding: 15px;
            border-radius: 6px;
            margin-bottom: 20px;
        }
        .alert-error {
            background: #fee2e2;
            color: #991b1b;
            border: 1px solid #fecaca;
        }
        .alert-success {
            background: #d1fae5;
            color: #065f46;
            border: 1px solid #a7f3d0;
        }
        .info-box {
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            border-radius: 6px;
            padding: 15px;
            margin-bottom: 20px;
        }
        .info-box p {
            color: #1e40af;
            margin-bottom: 5px;
        }
        .checkbox-group {
            display: flex;
            align-items: center;
            gap: 10px;
        }
        .checkbox-group input[type="checkbox"] {
            width: auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>SchoolPro V2.0.0</h1>
            <p>Installation Wizard</p>
        </div>
        <div class="content">
            <!-- Step Indicator -->
            <div class="step-indicator">
                <div class="step <?php echo $step >= '1' ? 'active' : ''; ?> <?php echo $step > '1' ? 'completed' : ''; ?>">1</div>
                <div class="step <?php echo $step >= '2' ? 'active' : ''; ?> <?php echo $step > '2' ? 'completed' : ''; ?>">2</div>
                <div class="step <?php echo $step >= '3' ? 'active' : ''; ?> <?php echo $step > '3' ? 'completed' : ''; ?>">3</div>
                <div class="step <?php echo $step >= '4' ? 'active' : ''; ?> <?php echo $step > '4' ? 'completed' : ''; ?>">4</div>
            </div>

            <!-- Error Messages -->
            <?php foreach ($errors as $error): ?>
                <div class="alert alert-error"><?php echo htmlspecialchars($error); ?></div>
            <?php endforeach; ?>

            <!-- Success Messages -->
            <?php foreach ($success as $msg): ?>
                <div class="alert alert-success"><?php echo htmlspecialchars($msg); ?></div>
            <?php endforeach; ?>

            <!-- Step 1: Database Configuration -->
            <?php if ($step === '1'): ?>
                <h2>Step 1: Database Configuration</h2>
                <p style="color: #6b7280; margin-bottom: 30px;">Enter your database connection details</p>
                
                <form method="POST">
                    <input type="hidden" name="step" value="1">
                    
                    <div class="form-group">
                        <label>Database Host</label>
                        <input type="text" name="db_host" value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>" required>
                    </div>
                    
                    <div class="form-group">
                        <label>Database Name</label>
                        <input type="text" name="db_name" value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'masomo_school_db'); ?>" required>
                    </div>
                    
                    <div class="form-group">
                        <label>Database Username</label>
                        <input type="text" name="db_user" value="<?php echo htmlspecialchars($_POST['db_user'] ?? 'root'); ?>" required>
                    </div>
                    
                    <div class="form-group">
                        <label>Database Password</label>
                        <input type="password" name="db_pass" value="<?php echo htmlspecialchars($_POST['db_pass'] ?? ''); ?>">
                    </div>
                    
                    <button type="submit" class="btn">Test Connection & Continue</button>
                </form>

            <!-- Step 2: Environment Configuration -->
            <?php elseif ($step === '2'): ?>
                <h2>Step 2: Environment Configuration</h2>
                <p style="color: #6b7280; margin-bottom: 30px;">Configure your application environment</p>
                
                <form method="POST">
                    <input type="hidden" name="step" value="2">
                    <input type="hidden" name="db_host" value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>">
                    <input type="hidden" name="db_name" value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'masomo_school_db'); ?>">
                    <input type="hidden" name="db_user" value="<?php echo htmlspecialchars($_POST['db_user'] ?? 'root'); ?>">
                    <input type="hidden" name="db_pass" value="<?php echo htmlspecialchars($_POST['db_pass'] ?? ''); ?>">
                    
                    <div class="form-group">
                        <label>Environment</label>
                        <select name="environment" required>
                            <option value="development" <?php echo ($_POST['environment'] ?? 'production') === 'development' ? 'selected' : ''; ?>>Development</option>
                            <option value="production" <?php echo ($_POST['environment'] ?? 'production') === 'production' ? 'selected' : ''; ?>>Production</option>
                        </select>
                    </div>
                    
                    <div class="form-group">
                        <label>Application Name</label>
                        <input type="text" name="app_name" value="<?php echo htmlspecialchars($_POST['app_name'] ?? 'SchoolPro V2.0.0'); ?>" required>
                    </div>
                    
                    <div class="info-box">
                        <p><strong>Note:</strong> Base URL will be auto-detected based on your domain. You can manually override it later in the .env file if needed.</p>
                    </div>
                    
                    <button type="submit" class="btn">Create Configuration & Continue</button>
                    <a href="?step=1" class="btn btn-secondary" style="text-decoration: none; display: inline-block; margin-left: 10px;">Back</a>
                </form>

            <!-- Step 3: Database Import -->
            <?php elseif ($step === '3'): ?>
                <h2>Step 3: Import Database</h2>
                <p style="color: #6b7280; margin-bottom: 30px;">Import the database schema and initial data</p>
                
                <form method="POST">
                    <input type="hidden" name="step" value="3">
                    <input type="hidden" name="db_host" value="<?php echo htmlspecialchars($_POST['db_host'] ?? 'localhost'); ?>">
                    <input type="hidden" name="db_name" value="<?php echo htmlspecialchars($_POST['db_name'] ?? 'masomo_school_db'); ?>">
                    <input type="hidden" name="db_user" value="<?php echo htmlspecialchars($_POST['db_user'] ?? 'root'); ?>">
                    <input type="hidden" name="db_pass" value="<?php echo htmlspecialchars($_POST['db_pass'] ?? ''); ?>">
                    <input type="hidden" name="environment" value="<?php echo htmlspecialchars($_POST['environment'] ?? 'production'); ?>">
                    <input type="hidden" name="app_name" value="<?php echo htmlspecialchars($_POST['app_name'] ?? 'SchoolPro V2.0.0'); ?>">
                    
                    <div class="info-box">
                        <p><strong>Ready to import database schema?</strong></p>
                        <p>This will create all necessary tables and initial data.</p>
                    </div>
                    
                    <div class="checkbox-group" style="margin-bottom: 20px;">
                        <input type="checkbox" name="import_schema" id="import_schema" checked>
                        <label for="import_schema" style="margin: 0;">Import database schema</label>
                    </div>
                    
                    <button type="submit" class="btn">Import Database & Complete Installation</button>
                    <a href="?step=2" class="btn btn-secondary" style="text-decoration: none; display: inline-block; margin-left: 10px;">Back</a>
                </form>

            <!-- Step 4: Installation Complete -->
            <?php elseif ($step === '4'): ?>
                <div style="text-align: center; padding: 40px 0;">
                    <div style="font-size: 64px; color: #10b981; margin-bottom: 20px;">✓</div>
                    <h2>Installation Complete!</h2>
                    <p style="color: #6b7280; margin: 20px 0 30px;">Your application has been successfully installed.</p>
                    
                    <div class="info-box" style="text-align: left; margin-bottom: 30px;">
                        <p><strong>Default Login Credentials:</strong></p>
                        <p>Email: <code>admin@school.co.ke</code></p>
                        <p>Password: <code>admin123</code></p>
                        <p style="margin-top: 15px; color: #dc2626;"><strong>⚠️ Important:</strong> Change the default password immediately after logging in!</p>
                    </div>
                    
                    <div class="info-box" style="text-align: left; margin-bottom: 30px; background: #fef3c7; border-color: #f59e0b;">
                        <p><strong>Security Recommendations:</strong></p>
                        <ul style="margin-left: 20px; margin-top: 10px;">
                            <li>Delete or rename <code>install.php</code> file</li>
                            <li>Set proper file permissions (755 for directories, 644 for files)</li>
                            <li>Review and update your .env file with production settings</li>
                            <li>Enable HTTPS in production</li>
                        </ul>
                    </div>
                    
                    <a href="index.php" class="btn" style="text-decoration: none; display: inline-block; padding: 15px 30px; font-size: 18px;">Go to Application</a>
                </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>

